### ISSUE TITLE
Create route for new challenge or modal

### ISSUE THREAD

**Issue by FeBotero** [KarineBrandelli/calendar-project50#17]
I think creating a route to add a new challenge or opening a modal with that option would be too much.

**Comment by wesleydmscn** [comment]
I'm glad for the interest in the project
Could you give a more in-depth description for this new feature? 😄 

@FeBotero

**Comment by FeBotero** [comment]
Okay.

I think about using the modal, where it opens after the selected day. A form with this route to add new habits or new challenges.

Type name and selection days

In React there is React-Modal, I don't know what it would be in electron.

**Comment by wesleydmscn** [comment]
Your idea is very cool, but in the premise of Project 50 there are specific challenges, this project is not like a _"Habit Tracker"_, but a, _"Journal of Project50"_. I recommend looking on **instagram** or **tiktok** for the hashtag `#Project50` to better understand. 😃 

### Project50 Rules:

1. WAKE UP BEFORE 8 A.M.
2. DO YOUR MORNING ROUTINE (1h no distractions).
3. EXERCISE FOR 1H A DAY.
4. READ 10 PAGES A DAY.
5. DEDICATE 1H TOWARDS A NEW SKILL.
6. FOLLOW A HEALTHY DIET.
7. TRACK YOUR DAILY PROGRESS IN A JOURNAL.
